# Generated by Django 6.0.3 on 2026-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pending_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
