# Generated by Django 6.0.3 on 2026-03-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
